print("Bienvenido a mi primer programa:  ")
apell=input("por favor escribe tu apellido:  ")
nom=input("ingrese su nombre:  ")
edad=input("Edad:  ")
print(".................................")
print(apell.upper())
print(nom.title())
print(edad)
#capitalize sirve para poner la primera letra en mayuscula (Esto es texto)
#title sirve para poner la primera letra de cada palabra (Esto Es Texto)
#upper sirve para poner todo en mayuscula (ESTO ES TEXTO)
#lower sirve para poner todo en minuscula (esto es texto)